# Generated by Django 6.0.5 on 2026-05-28 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.IntegerField(blank=True, null=True)),
                ('modified_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.IntegerField(blank=True, null=True)),
                ('modified_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.IntegerField(blank=True, null=True)),
                ('modified_id', models.IntegerField(blank=True, null=True)),
                ('table_number', models.IntegerField(unique=True)),
                ('seating_capacity', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=True)),
                ('location', models.CharField(choices=[('TERRAZA', 'Terraza'), ('INTERIOR', 'Salón Interior'), ('VIP', 'Zona VIP')], default='INTERIOR', max_length=20)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.IntegerField(blank=True, null=True)),
                ('modified_id', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=155)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.menucategory')),
            ],
            options={
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.IntegerField(blank=True, null=True)),
                ('modified_id', models.IntegerField(blank=True, null=True)),
                ('reservation_date', models.DateTimeField()),
                ('guest_count', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.customer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFirstApplication.table')),
            ],
            options={
                'ordering': ['-reservation_date'],
                'constraints': [models.UniqueConstraint(fields=('table', 'reservation_date'), name='unique_table_reservation')],
            },
        ),
    ]
